### ISSUE TITLE
no output file

### ISSUE THREAD

**Issue by Puputnik** [jyhehir/mobster#14]
Hello, my mobster run seems to be finished correctly, however i'm not getting any *_prediction.txt file

INFO	2018-06-19 11:26:34	SinglePassSamProgram	Processed  47.000.000 records.
INFO	2018-06-19 11:26:50	SinglePassSamProgram	Processed  48.000.000 records.
INFO	2018-06-19 11:27:07	SinglePassSamProgram	Processed  49.000.000 records.
INFO	2018-06-19 11:27:25	SinglePassSamProgram	Processed  50.000.000 records.
INFO	2018-06-19 11:27:41	ProcessExecutor	null device 
INFO	2018-06-19 11:27:41	ProcessExecutor	          1 
[Tue Jun 19 11:27:41 CEST 2018] net.sf.picard.analysis.CollectInsertSizeMetrics done. Elapsed time: 14,25 minutes.
Runtime.totalMemory()=207618048
Exit value: 0
Exception in thread "main" java.lang.NumberFormatException: For input string: "378,964003"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at org.umcn.me.pairedend.Mobster.main(Mobster.java:96)

any clue?

Thanks a lot!

**Comment by Puputnik** [comment]
P.S. I forgot to say that the *_hist.pdf and *_insertstats files have been generated

**Comment by jyhehir** [comment]
Yes, I have seen this before. Probably your JVM is not installed with local english as default. Does this make sense?This can be overridden at the command lineeg
-Duser.country=US -Duser.language=en
Regards,Jayne    On Tuesday, 19 June 2018, 11:43:39 am GMT+2, Puputnik <notifications@github.com> wrote:  
 
 
Hello, my mobster run seems to be finished correctly, however i'm not getting any *_prediction.txt file

INFO 2018-06-19 11:26:34 SinglePassSamProgram Processed 47.000.000 records.
INFO 2018-06-19 11:26:50 SinglePassSamProgram Processed 48.000.000 records.
INFO 2018-06-19 11:27:07 SinglePassSamProgram Processed 49.000.000 records.
INFO 2018-06-19 11:27:25 SinglePassSamProgram Processed 50.000.000 records.
INFO 2018-06-19 11:27:41 ProcessExecutor null device
INFO 2018-06-19 11:27:41 ProcessExecutor 1
[Tue Jun 19 11:27:41 CEST 2018] net.sf.picard.analysis.CollectInsertSizeMetrics done. Elapsed time: 14,25 minutes.
Runtime.totalMemory()=207618048
Exit value: 0
Exception in thread "main" java.lang.NumberFormatException: For input string: "378,964003"
at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
at java.lang.Double.parseDouble(Double.java:538)
at org.umcn.me.pairedend.Mobster.main(Mobster.java:96)

any clue?

Thanks a lot!

**Comment by Puputnik** [comment]
tried with the -Duser.country=US -Duser.language=en options, still getting the same error unfortunately.

**Comment by jyhehir** [comment]
just to double check, which version of Mobster are you using. It really looks like the jvm is getting confused with the locales

**Comment by josesovaz** [comment]
Hello jyhehir,

I have exactly the same output error using the example provided:

WARNING	2019-05-28 12:07:30	SinglePassSamProgram	File reports sort order 'unsorted', assuming it's coordinate sorted anyway.
INFO	2019-05-28 12:07:33	SinglePassSamProgram	Processed   1.000.000 records.
INFO	2019-05-28 12:07:35	SinglePassSamProgram	Processed   2.000.000 records.
INFO	2019-05-28 12:07:36	SinglePassSamProgram	Processed   3.000.000 records.
INFO	2019-05-28 12:07:38	SinglePassSamProgram	Processed   4.000.000 records.
INFO	2019-05-28 12:07:39	SinglePassSamProgram	Processed   5.000.000 records.
INFO	2019-05-28 12:07:41	SinglePassSamProgram	Processed   6.000.000 records.
INFO	2019-05-28 12:07:42	SinglePassSamProgram	Processed   7.000.000 records.
INFO	2019-05-28 12:07:43	SinglePassSamProgram	Processed   8.000.000 records.
INFO	2019-05-28 12:07:45	SinglePassSamProgram	Processed   9.000.000 records.
INFO	2019-05-28 12:07:46	SinglePassSamProgram	Processed  10.000.000 records.
INFO	2019-05-28 12:07:48	SinglePassSamProgram	Processed  11.000.000 records.
INFO	2019-05-28 12:07:49	SinglePassSamProgram	Processed  12.000.000 records.
INFO	2019-05-28 12:07:50	SinglePassSamProgram	Processed  13.000.000 records.
INFO	2019-05-28 12:08:05	ProcessExecutor	null device
INFO	2019-05-28 12:08:05	ProcessExecutor	          1
[Tue May 28 12:08:05 CEST 2019] net.sf.picard.analysis.CollectInsertSizeMetrics done. Elapsed time: 0,59 minutes.
Runtime.totalMemory()=2039414784
Exit value: 0
Exception in thread "main" java.lang.NumberFormatException: For input string: "310,791697"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at org.umcn.me.pairedend.Mobster.configureAndRunPicard(Mobster.java:131)
	at org.umcn.me.pairedend.Mobster.main(Mobster.java:58)

I tried to solve this issue with the -Duser.country=US -Duser.language=en but it didn't work, it gives the same error again.

Regards,

Jose

**Comment by jyhehir** [comment]
Hello,
Thanks for trying to suggested fix, I will look further into why the setting is not passed onto picard, internally.But in the mean time as a work around you could try to run pcard, for the insert size metrics, and then set this in mobster.properties.
Regards,Jayne
    On Tuesday, 28 May 2019, 12:14:13 pm GMT+2, josesovaz <notifications@github.com> wrote:  
 
 
Hello jyhehir,

I have exactly the same output error using the example provided:

WARNING 2019-05-28 12:07:30 SinglePassSamProgram File reports sort order 'unsorted', assuming it's coordinate sorted anyway.
INFO 2019-05-28 12:07:33 SinglePassSamProgram Processed 1.000.000 records.
INFO 2019-05-28 12:07:35 SinglePassSamProgram Processed 2.000.000 records.
INFO 2019-05-28 12:07:36 SinglePassSamProgram Processed 3.000.000 records.
INFO 2019-05-28 12:07:38 SinglePassSamProgram Processed 4.000.000 records.
INFO 2019-05-28 12:07:39 SinglePassSamProgram Processed 5.000.000 records.
INFO 2019-05-28 12:07:41 SinglePassSamProgram Processed 6.000.000 records.
INFO 2019-05-28 12:07:42 SinglePassSamProgram Processed 7.000.000 records.
INFO 2019-05-28 12:07:43 SinglePassSamProgram Processed 8.000.000 records.
INFO 2019-05-28 12:07:45 SinglePassSamProgram Processed 9.000.000 records.
INFO 2019-05-28 12:07:46 SinglePassSamProgram Processed 10.000.000 records.
INFO 2019-05-28 12:07:48 SinglePassSamProgram Processed 11.000.000 records.
INFO 2019-05-28 12:07:49 SinglePassSamProgram Processed 12.000.000 records.
INFO 2019-05-28 12:07:50 SinglePassSamProgram Processed 13.000.000 records.
INFO 2019-05-28 12:08:05 ProcessExecutor null device
INFO 2019-05-28 12:08:05 ProcessExecutor 1
[Tue May 28 12:08:05 CEST 2019] net.sf.picard.analysis.CollectInsertSizeMetrics done. Elapsed time: 0,59 minutes.
Runtime.totalMemory()=2039414784
Exit value: 0
Exception in thread "main" java.lang.NumberFormatException: For input string: "310,791697"
at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
at java.lang.Double.parseDouble(Double.java:538)
at org.umcn.me.pairedend.Mobster.configureAndRunPicard(Mobster.java:131)
at org.umcn.me.pairedend.Mobster.main(Mobster.java:58)

I tried to solve this issue with the -Duser.country=US -Duser.language=en but it didn't work, it gives the same error again.

Regards,

Jose

**Comment by josesovaz** [comment]
Finally, I could fix the issue. As you said, the problem was with the locale. I think If the locale is not in english as default, it gives the error because it can't read the "," instead of "." in the decimal.

I have set the locale in english using the following command in the terminal:
export LANG=en_US.utf8

Then it works.

Thanks,

jose

**Comment by jyhehir** [comment]
Excellent, thanks for working it out.
    On Friday, 31 May 2019, 3:57:41 pm GMT+2, josesovaz <notifications@github.com> wrote:  
 
 
Finally, I could fix the issue. As you said, the problem was with the locale. I think If the locale is not in english as default, it gives the error because it can't read the "," instead of "." in the decimal.

I have set the locale in english using the following command in the terminal:
export LANG=en_US.utf8

Then it works.

Thanks,

jose
