### ISSUE TITLE
Test run issues: Picard error and MobileInsertions-1.0-SNAPSHOT.jar does not exist

### ISSUE THREAD

**Issue by npaulat** [jyhehir/mobster#29]
Hello,

I have just installed Mobster, and did not notice any errors during installation. However, when trying to run Mobster with the sample bam command cd target
java -Xmx8G -jar MobileInsertions-0.2.4.1.jar \
    -properties Mobster.properties \
    -out TestSample

I receive the following error:

java -Xmx8G -jar MobileInsertions-0.2.4.1.jar -properties Mobster.properties -out TestSample
[Thu Aug 22 10:14:52 CDT 2019] net.sf.picard.analysis.CollectInsertSizeMetrics HISTOGRAM_FILE=TestSample_hist.pdf INPUT=../test_files/chr12_wgs_3000ins_100excl_10x_bwadef.bam OUTPUT=TestSample_insertstats STOP_AFTER=50000000 VALIDATION_STRINGENCY=LENIENT DEVIATIONS=10.0 MINIMUM_PCT=0.05 METRIC_ACCUMULATION_LEVEL=[ALL_READS] ASSUME_SORTED=true VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
[Thu Aug 22 10:14:52 CDT 2019] Executing as npaulat@compute-7-16 on Linux 3.10.0-693.21.1.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_152-release-1056-b12; Picard version: 1.73(1234)
WARNING 2019-08-22 10:14:52 SinglePassSamProgram File reports sort order 'unsorted', assuming it's coordinate sorted anyway.
INFO 2019-08-22 10:14:55 SinglePassSamProgram Processed 1,000,000 records.
INFO 2019-08-22 10:14:57 SinglePassSamProgram Processed 2,000,000 records.
INFO 2019-08-22 10:14:59 SinglePassSamProgram Processed 3,000,000 records.
INFO 2019-08-22 10:15:02 SinglePassSamProgram Processed 4,000,000 records.
INFO 2019-08-22 10:15:04 SinglePassSamProgram Processed 5,000,000 records.
INFO 2019-08-22 10:15:06 SinglePassSamProgram Processed 6,000,000 records.
INFO 2019-08-22 10:15:08 SinglePassSamProgram Processed 7,000,000 records.
INFO 2019-08-22 10:15:10 SinglePassSamProgram Processed 8,000,000 records.
INFO 2019-08-22 10:15:13 SinglePassSamProgram Processed 9,000,000 records.
INFO 2019-08-22 10:15:15 SinglePassSamProgram Processed 10,000,000 records.
INFO 2019-08-22 10:15:17 SinglePassSamProgram Processed 11,000,000 records.
INFO 2019-08-22 10:15:19 SinglePassSamProgram Processed 12,000,000 records.
INFO 2019-08-22 10:15:21 SinglePassSamProgram Processed 13,000,000 records.
[Thu Aug 22 10:15:39 CDT 2019] net.sf.picard.analysis.CollectInsertSizeMetrics done. Elapsed time: 0.78 minutes.
Runtime.totalMemory()=1912602624
FAQ: http://sourceforge.net/apps/mediawiki/picard/index.php?title=Main_Page
Exception in thread "main" net.sf.picard.PicardException: Unexpected exception executing [Rscript /tmp/npaulat/script2642089209349607558.R /lustre/work/npaulat/mobster/target/TestSample_insertstats /lustre/work/npaulat/mobster/target/TestSample_hist.pdf chr12_wgs_3000ins_100excl_10x_bwadef.bam]
at net.sf.picard.util.ProcessExecutor.execute(ProcessExecutor.java:102)
at net.sf.picard.util.ProcessExecutor.execute(ProcessExecutor.java:78)
at net.sf.picard.util.RExecutor.executeFromFile(RExecutor.java:73)
at net.sf.picard.util.RExecutor.executeFromClasspath(RExecutor.java:55)
at net.sf.picard.analysis.CollectInsertSizeMetrics.finish(CollectInsertSizeMetrics.java:133)
at net.sf.picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:145)
at net.sf.picard.analysis.SinglePassSamProgram.doWork(SinglePassSamProgram.java:54)
at net.sf.picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:177)
at net.sf.picard.cmdline.CommandLineProgram.instanceMainWithExit(CommandLineProgram.java:119)
at net.sf.picard.analysis.CollectInsertSizeMetrics.main(CollectInsertSizeMetrics.java:82)
Caused by: java.io.IOException: Cannot run program "Rscript": error=2, No such file or directory
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
at java.lang.Runtime.exec(Runtime.java:620)
at java.lang.Runtime.exec(Runtime.java:485)
at net.sf.picard.util.ProcessExecutor.execute(ProcessExecutor.java:93)
... 9 more
Caused by: java.io.IOException: error=2, No such file or directory
at java.lang.UNIXProcess.forkAndExec(Native Method)
at java.lang.UNIXProcess.(UNIXProcess.java:247)
at java.lang.ProcessImpl.start(ProcessImpl.java:134)
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
... 12 more
Exit value: 1

It then continues on with other steps, which appear to run without error.

In addition, when trying to run java -Xmx8G -jar MobileInsertions-1.0-SNAPSHOT.jar \
    -properties Mobster_latest.properties \
    -in input.bam \
    -sn test_sample \
    -out mobster_test

I get: "Error: Unable to access jarfile MobileInsertions-1.0-SNAPSHOT.jar"
I can't figure out where the MobileInsertions-1.0-SNAPSHOT.jar or the Mobster_latest.properties file would exist either. 

Any help would be greatly appreciated.

**Comment by npaulat** [comment]
I reinstalled, and now receive the following error:

Exception in thread "main" net.sf.picard.PicardException: Unexpected exception executing [Rscript /tmp/npaulat/script3310977848820166929.R /lustre/work/npaulat/mobster/target/TestSample_insertstats /lustre/work/npaulat/mobster/target/TestSample_hist.pdf chr12_wgs_3000ins_100excl_10x_bwadef.bam]
        at net.sf.picard.util.ProcessExecutor.execute(ProcessExecutor.java:102)
        at net.sf.picard.util.ProcessExecutor.execute(ProcessExecutor.java:78)
        at net.sf.picard.util.RExecutor.executeFromFile(RExecutor.java:73)
        at net.sf.picard.util.RExecutor.executeFromClasspath(RExecutor.java:55)
        at net.sf.picard.analysis.CollectInsertSizeMetrics.finish(CollectInsertSizeMetrics.java:133)
        at net.sf.picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:145)
        at net.sf.picard.analysis.SinglePassSamProgram.doWork(SinglePassSamProgram.java:54)
        at net.sf.picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:177)
        at net.sf.picard.cmdline.CommandLineProgram.instanceMainWithExit(CommandLineProgram.java:119)
        at net.sf.picard.analysis.CollectInsertSizeMetrics.main(CollectInsertSizeMetrics.java:82)
Caused by: java.io.IOException: Cannot run program "Rscript": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:620)
        at java.lang.Runtime.exec(Runtime.java:485)
        at net.sf.picard.util.ProcessExecutor.execute(ProcessExecutor.java:93)
        ... 9 more
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 12 more
Exit value: 1
0 [main] INFO org.umcn.me.pairedend.PotentialMEIReadFinder  - Using infile(s): ../test_files/chr12_wgs_3000ins_100excl_10x_bwadef.bam
2 [main] INFO org.umcn.me.pairedend.PotentialMEIReadFinder  - Using out prefix: TestSample
2 [main] INFO org.umcn.me.pairedend.PotentialMEIReadFinder  - Used mapping tool: unspecified
2 [main] INFO org.umcn.me.pairedend.PotentialMEIReadFinder  - Including split reads: true
2 [main] INFO org.umcn.me.pairedend.PotentialMEIReadFinder  - Maximum records in memory: 10000000
2 [main] INFO org.umcn.me.pairedend.PotentialMEIReadFinder  - Temp directory: /tmp/mob_1875091056885312
2 [main] INFO org.umcn.me.pairedend.PotentialMEIReadFinder  - Split reads should have min avg qual of: 10
2 [main] INFO org.umcn.me.pairedend.PotentialMEIReadFinder  - Minimum clipping of: 27
2 [main] INFO org.umcn.me.pairedend.PotentialMEIReadFinder  - Maximum clipping of other side: 7
2 [main] INFO org.umcn.me.pairedend.PotentialMEIReadFinder  - Using mapq of: 20for defining anchors
2 [main] INFO org.umcn.me.pairedend.PotentialMEIReadFinder  - Number of samples detected: 1
4 [main] INFO org.umcn.me.pairedend.PotentialMEIReadFinder  - [PMRF] detected one sample, not modifying RG's
65 [main] INFO org.umcn.me.pairedend.PotentialMEIReadFinder  - Skipping UM pairs?: false
110 [main] INFO org.umcn.me.pairedend.PotentialMEIReadFinder  - Processed 0 mobile read pairs that have split read or certain size
111 [main] INFO org.umcn.me.pairedend.PotentialMEIReadFinder  - Processed 0 mobile read pairs that have split read or certain size
43290 [main] INFO org.umcn.me.pairedend.PotentialMEIReadFinder  - Found nr of potential mobile pairs supporting MEI events: 69318
43290 [main] INFO org.umcn.me.pairedend.PotentialMEIReadFinder  - Of which 18664 are of split-read nature.
43294 [main] INFO org.umcn.me.pairedend.PotentialMEIReadFinder  - [PMRF] PotentialMEIReadFinder ran in : 0 min, 43 sec
- loading jump key database into memory... finished.
- loading jump positions database into memory... finished.
/bin/sh: line 1: 120030 Segmentation fault      (core dumped) MosaikAligner -in TestSample_potential.dat -out TestSample_mappedpotentials -ia ../resources/mobiome/54_mobiles_inclHERVK.dat -hs 9 -mmp 0.1 -act 20 -j ../resources/mobiome/54_mobiles_inclHERVK_hs9 -p 2 -annpe ../resources/MOSAIK/2.1.26.pe.100.0065.ann -annse ../resources/MOSAIK/2.1.26.se.100.005.ann -quiet
Exit value: 139
43778 [main] FATAL Mobster  - Mobiome mapping finished with non-normal exit value: 139
43778 [main] FATAL Mobster  - Therefore Mobster execution is terminated

**Comment by meboussaha** [comment]
Dear npaulat,
I was wondering whether you have solved your issue and where did you find MobileInsertions-1.0-SNAPSHOT.jar?
Thank you for your response
Mekki

**Comment by npaulat** [comment]
I solved the issue. The MobileInsertions-1.0-SNAPSHOT.jar is just the old name for the MobileInsertions-0.2.4.1.jar, and was not updated in the example commands in the README. As for the Picard errors, they are warnings from some sort of utility, but Mobster still runs to completion.

**Comment by meboussaha** [comment]
OK thanks a lot for the tip. I also figure dit out lately by testing the MobileInsertions-0.2.4.1.jar and option bwa-mem.
Cheers

De : npaulat <notifications@github.com>
Envoyé : mercredi 6 novembre 2019 00:07
À : jyhehir/mobster <mobster@noreply.github.com>
Cc : Mekki Boussaha <mekki.boussaha@inra.fr>; Comment <comment@noreply.github.com>
Objet : Re: [jyhehir/mobster] Test run issues: Picard error and MobileInsertions-1.0-SNAPSHOT.jar does not exist (#29)


I solved the issue. The MobileInsertions-1.0-SNAPSHOT.jar is just the old name for the MobileInsertions-0.2.4.1.jar, and was not updated in the example commands in the README. As for the Picard errors, they are warnings from some sort of utility, but Mobster still runs to completion.
