### ISSUE TITLE
java index out of bounds exception

### ISSUE THREAD

**Issue by th-koechling** [jyhehir/mobster#42]
Hello,

after running Mobster successfully with the provided BAM file, I adapted the Mobster.properties config-file and tried to analyze a BAM file generated with bwa mem. After working seemingly fine for a time the program crashes at this point with a Java ArrayIndexOutOfBoundsException. The error is too low-level for me to understand:

25968 [main] INFO AnchorClusterer  - Nr of mate clusters with merged split clusters: 0
25972 [main] INFO AnchorClusterer  - Total nr of split clusters without mate support: 0
25997 [main] INFO AnchorClusterer  - Number of merged Mobile Predictions: 0
25997 [main] INFO AnchorClusterer  - Number of predictions before merging: 2
25997 [main] INFO AnchorClusterer  - Number of predictions after merging: 2
25997 [main] INFO AnchorClusterer  - 1 predictions did not meet the minimum required read support of: 5
32094 [main] INFO AnchorClusterer  - filtered alu: 0
32095 [main] INFO AnchorClusterer  - filtered sva: 0
32095 [main] INFO AnchorClusterer  - filtered l1: 1
32095 [main] INFO AnchorClusterer  - filtered herv (hervk): 0
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
	at java.util.Vector.get(Vector.java:751)
	at org.umcn.me.pairedend.AnchorClusterer.writePredictionsToFile(Unknown Source)
	at org.umcn.me.pairedend.AnchorClusterer.runFromPropertiesFile(Unknown Source)
	at org.umcn.me.pairedend.Mobster.main(Unknown Source)
(base) genuser@jars -> 

Any help to resolve this would be much appreciated. 

Kind regards

Thorsten

**Comment by jyhehir** [comment]
Agree its not very helpful error message.  
Looking at the code, I'm guessing that it is crashing when trying to write out the header of the cluster file. Can you double check that the properties file is well formatted. No parameters without values etc.

Regards,
Jayne
